### ISSUE TITLE
Need definitions for more languages

### ISSUE THREAD

**Issue by misterbuckley** [misterbuckley/vim-definitive#1]
- [x] javascript/typescript
- [x] python
- [x] ruby
- [x] vim
- [ ] c/c++
- [x] php
- [x] scala
- [x] elixir

**Comment by NKBelousov** [comment]
Would you consider adding PHP support as well?

**Comment by misterbuckley** [comment]
@NKBelousov Of course! I can take a crack at it, but I don't work in php much, so if you or someone else who does could come up with a regex to match var/function definitions in php, that'd be greatly appreciated :)

**Comment by execb5** [comment]
What do you think of adding support for Elixir? Syntax is very similar to ruby.
 I'm using a regex that's not perfect for elixir, I kinda adapted your ruby regex.

**Comment by flipsi** [comment]
I added definitions for Scala in #10.

**Comment by misterbuckley** [comment]
@NKBelousov Added basic PHP support in 749bd73

**Comment by NKBelousov** [comment]
Awesome, going to check this out soon! Thank you!

**Comment by NKBelousov** [comment]
@misterbuckley my tests show it doesn't work for PHP classes/interfaces, even in the same file but it found occurences in another files (I've tried to find definition of "User" inside of "User" class but it found statements which use User::something() inside other files).

It's an old project written in PHP 5.6. I could provide minimal test suite to reproduce, would you be able to give it a look?

**Comment by misterbuckley** [comment]
@NKBelousov I can take a look. If you could give me a test suite that'd be great.

@execb5 Sorry for taking so long to get back to you. I've added support for Elixir in 265f8a7. Let me know if you have any trouble with it. I cloned a couple elixir projects off github and tested it out and the regex I came up with seems to work decently well, but I don't use the language on a daily basis so it might not be perfect.

**Comment by misterbuckley** [comment]
gonna close this as support for c/c++ is unlikely due to the complexity of the necessary grep string and demand for other languages is apparently low
