### ISSUE TITLE
Add ability to look for definitions in other filetypes

### ISSUE THREAD

**Issue by misterbuckley** [misterbuckley/vim-definitive#11]
i.e. If I'm in a handlebars or erb template, I want to be able to search for the definition of a variable in javascript or ruby, respectively

**Comment by erasmodanarni** [comment]
I'm using vue.js and in its single file you have code block written in Javascript, html (and css). For the time being, how could I search for the definitions of at least the javascript code? TIA

**Comment by misterbuckley** [comment]
@erasmodanarni If the filetype is `javascript` then it should just work. If it's not working, you can do `:set ft?` to figure out what the filetype is and add a new key to g:definitive_definitions using the extends syntax, e. g.:
let g:definitive_definitions = {
    \ 'insert.filetype.here': { 'extends': 'javascript' }
    \ }

**Comment by misterbuckley** [comment]
fixed in f30571aec78ebb9981ee979d3033a58842bd4fd1
