### ISSUE TITLE
Allow filetypes to extend one another

### ISSUE THREAD

**Issue by NKBelousov** [misterbuckley/vim-definitive#9]
Hi there! Maybe consider adding a way for filetypes to extend one another. Right now I am forced to duplicate my regex for both javascript and javascript.jsx. 

eg. emmet:
```
let g:user_emmet_settings = {
  \  'javascript.jsx' : {
  \      'extends' : 'jsx',
  \  },
  \}
```

**Comment by misterbuckley** [comment]
Good idea, I was kinda thinking of doing something like this. I'll go ahead and implement this shortly

**Comment by misterbuckley** [comment]
done in fddd69895530dfb4ea6e13ec2c3ec089dbfa31aa
